### ISSUE TITLE
App auto-closes

### ISSUE THREAD

**Issue by Petethehe** [madhurbhargava/AndroidWarehouseMonitor#1]
Dear Mr. Bhargava,
I am following through your very nice book and reached now chapter 6. Unfortunately with this code implementation the app automatically closes on the cellphone with the notification: "Location permission not granted". Could you please resolve this issue? Unfortunately I am not able to make it work properly. 

Best regards,
Peter Ambrosch

**Comment by Petethehe** [comment]
I had to add permissions of coarse location in the activity.xml. Finally figured it out directly after I wrote the issue. Sorry and have a good day sir.

**Comment by madhurbhargava** [comment]
Nice to know that you were able to get the solution - Since it was already mentioned on Page 84 and then on Page 131 to add the permissions, hence it was not repeated for every project but the permissions mentioned on those pages are mandatory permissions indeed. Cheers!
